name: Deploy to GitHub Pages

# Run this workflow every time you push to the `main` branch
on:
  push:
    branches: [ main ]

# Set permissions for the GITHUB_TOKEN for deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4

      - name: Replace Firebase config placeholders
        run: |
          # Find and replace each placeholder in index.html with the secret value
          # This command (sed) finds the placeholder (e.g., YOUR_API_KEY_HERE)
          # and replaces it with the secret value you set in your repo settings.
          sed -i "s/YOUR_API_KEY_HERE/${{ secrets.FIREBASE_API_KEY }}/g" index.html
          sed -i "s/YOUR_AUTH_DOMAIN_HERE/${{ secrets.FIREBASE_AUTH_DOMAIN }}/g" index.html
          sed -i "s/YOUR_PROJECT_ID_HERE/${{ secrets.FIREBASE_PROJECT_ID }}/g" index.html
          sed -i "s/YOUR_STORAGE_BUCKET_HERE/${{ secrets.FIREBASE_STORAGE_BUCKET }}/g" index.html
          sed -i "s/YOUR_MESSAGING_SENDER_ID_HERE/${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}/g" index.html
          sed -i "s/YOUR_APP_ID_HERE/${{ secrets.FIREBASE_APP_ID }}/g" index.html
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload the modified index.html
          path: '.'

  deploy:
    # This job needs the build job to finish first
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

